"""initial

Revision ID: 5c3ab6128397
Revises: 
Create Date: 2026-06-27 00:49:16.072619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c3ab6128397'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recompensas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('costo_puntos', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('imagen_url', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('apellido', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('rol', sa.Enum('administrador', 'entidad', 'usuario', name='rol_usuario'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('puntos_totales', sa.Integer(), nullable=False),
    sa.Column('foto_url', sa.Text(), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('canjes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('recompensa_id', sa.UUID(), nullable=False),
    sa.Column('puntos_usados', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'entregado', 'cancelado', name='estado_canje'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('procesado_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recompensa_id'], ['recompensas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entidades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_creador_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('tipo', sa.Enum('veterinaria', 'hospital', 'policia', 'otro', name='tipo_entidad'), nullable=False),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('email_contacto', sa.String(length=150), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_creador_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('puntos_transacciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('asignacion_manual', 'bono_reporte', 'bono_encontrado', 'canje', name='tipo_punto'), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entidad_usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entidad_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('asignado_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entidad_id'], ['entidades.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entidad_id', 'user_id', name='uq_entidad_usuario')
    )
    op.create_table('publicaciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('autor_id', sa.UUID(), nullable=False),
    sa.Column('entidad_id', sa.UUID(), nullable=False),
    sa.Column('tipo_publicacion', sa.Enum('evento', 'campana', 'adopcion', 'voluntariado', name='tipo_publicacion'), nullable=False),
    sa.Column('estado', sa.Enum('borrador', 'publicado', 'archivado', name='estado_publicacion_pub'), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('fecha_evento', sa.DateTime(), nullable=True),
    sa.Column('lugar_evento', sa.String(length=200), nullable=True),
    sa.Column('cupos_disponibles', sa.Integer(), nullable=True),
    sa.Column('especie_mascota', sa.String(length=80), nullable=True),
    sa.Column('raza_mascota', sa.String(length=80), nullable=True),
    sa.Column('edad_mascota', sa.Integer(), nullable=True),
    sa.Column('sexo_mascota', sa.String(length=10), nullable=True),
    sa.Column('castrado', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['autor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['entidad_id'], ['entidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reportes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('creador_id', sa.UUID(), nullable=False),
    sa.Column('entidad_id', sa.UUID(), nullable=True),
    sa.Column('tipo_reporte', sa.Enum('persona_desaparecida', 'animal_desaparecido', 'accidente', 'vulnerabilidad', name='tipo_reporte'), nullable=False),
    sa.Column('subtipo_accidente', sa.Enum('atropello', 'desastre_natural', 'incendio', 'otro', name='subtipo_accidente'), nullable=True),
    sa.Column('estado_publicacion', sa.Enum('pendiente', 'aceptado', 'rechazado', name='estado_publicacion_reporte'), nullable=False),
    sa.Column('estado_resolucion', sa.Enum('activo', 'encontrado', 'atendido', 'cerrado', name='estado_resolucion'), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('nombre_desaparecido', sa.String(length=120), nullable=True),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('raza_especie', sa.String(length=80), nullable=True),
    sa.Column('color_descripcion', sa.Text(), nullable=True),
    sa.Column('ultima_ubicacion', sa.Text(), nullable=True),
    sa.Column('latitud', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitud', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('fecha_desaparicion', sa.DateTime(), nullable=True),
    sa.Column('descripcion_vulnerabilidad', sa.Text(), nullable=True),
    sa.Column('encontrado', sa.Boolean(), nullable=False),
    sa.Column('found_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creador_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['entidad_id'], ['entidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publicacion_imagenes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('publicacion_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['publicacion_id'], ['publicaciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reporte_imagenes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reporte_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['reporte_id'], ['reportes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reporte_validaciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reporte_id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.Enum('aceptado', 'rechazado', name='decision_validacion'), nullable=False),
    sa.Column('motivo_rechazo', sa.Text(), nullable=True),
    sa.Column('validated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reporte_id'], ['reportes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reporte_validaciones')
    op.drop_table('reporte_imagenes')
    op.drop_table('publicacion_imagenes')
    op.drop_table('reportes')
    op.drop_table('publicaciones')
    op.drop_table('entidad_usuarios')
    op.drop_table('puntos_transacciones')
    op.drop_table('entidades')
    op.drop_table('canjes')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('recompensas')
    # ### end Alembic commands ###
