"""add_verificacion_identidad

Revision ID: edd677eba8cd
Revises: 2459ad28b21f
Create Date: 2026-06-27 09:45:16.644958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edd677eba8cd'
down_revision: Union[str, None] = '2459ad28b21f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verificaciones_identidad',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('url_anverso', sa.Text(), nullable=False),
    sa.Column('url_reverso', sa.Text(), nullable=False),
    sa.Column('estado', sa.Enum('pendiente', 'verificado', 'rechazado', name='estado_verificacion'), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.Column('motivo_rechazo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('verificado', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verificado')
    op.drop_table('verificaciones_identidad')
    # ### end Alembic commands ###
